### ISSUE TITLE
Lag and visual glitches with new Impeller render engine

### ISSUE THREAD

**Issue by user425846** [notDmDrl/pull_down_button#10]
Hi! Thank you so much for this package, its absolutely awesome! 

However, i was having issues with a lot of lagging and i finally figured out what it was. I had the new Impeller render engine turned on for my iOS project, which caused the lagging and the visual issues. I have attached 2 videos of non Impeller vs. Impeller. Tried it both on a real device and on the simulator.

It would be awesome if you could release an update for this package!

https://user-images.githubusercontent.com/100499696/210103704-4c7112dd-d673-409f-ab1e-c053952a870c.mp4

https://user-images.githubusercontent.com/100499696/210103712-7a5bf9d8-2862-40d5-9df9-ab16426465b0.mp4

**Comment by notDmDrl** [comment]
Hi @user425846,

Based of of your first video it looks like impeller itself is not handling blur correctly right now (no blur whatsoever, and quite possibly this is the source of lag to).

Could you try using fully opaque color in the meantime? This will result in no blur used, so it should work with impeller with any further problems I hope.

Unfortunately I am on holiday vacation right now, so the earliest I can look into it in more closely is in a week.

**Comment by user425846** [comment]
Thanks for the quick reply! So i tried setting a fully opaque background color. The result: It fixed the lagging issue on the Simulator but NOT on the real device (iPhone 13 Pro). Also it shows some weird lines below some of the items. These lines are also at different positions at the simulator and the real device, but they do appear on both. I attached a video of the real device to this reply. This line issue does not appear without impeller turned on.

And next week would be great, enjoy your vacation!

https://user-images.githubusercontent.com/100499696/210130218-0c0fce8f-da97-4d96-afa4-9505ef8e6930.MP4

**Comment by notDmDrl** [comment]
> Also it shows some weird lines below some of the items.

Yeah, i also noticed those while trying out impeller in one of my other projects. From my observations, it appears that those lines are some part of a glyph that show up when you animate `Text` or change its content. Looks like it's another impeller specific issue.

---

> It fixed the lagging issue on the Simulator but NOT on the real device (iPhone 13 Pro)

Will look into this.

**Comment by notDmDrl** [comment]
Hi @user425846 

So i tested an example app and here are my observations:

#### On iPhone 7 Plus and iPhone 11 Pro Max (profile)

1. Blur was rendered correctly (not like on your first video);
2. There where not any random glyph parts (not like on your third video);
3. Performance wise it was really bad (average frame render time was way over 32ms, non impeller was around 4ms) for whole application, not just pull-down menu. Although, as i was expecting, using fully opaque background color indeed improves frame rate a bit.

#### On Simulator (debug)

1. Blur was rendered correctly;
2. No any random glyph parts;
3. Similar to 7 plus - pretty noticeable lag, opaque background slightly better. 

--- 

Worth mentioning that i used latest beta (**3.7.0-1.2.pre**) for tests. Seems like 1. and 2. were already fixed.

Performance wise, I'd say its better to wait at least for beta version of impeller. Right now it's too unfinished to begin any optimisation works.
Hopefully, said beta will be released after upcoming [Flutter Forward](https://twitter.com/FlutterDev/status/1604907566487568384?s=20&t=6mU3FO0I8lBthQ1z6p9MJA).

**Comment by notDmDrl** [comment]
Based on release notes for [Flutter 3.7.0](https://medium.com/flutter/whats-new-in-flutter-3-7-38cbea71133c) Impeller is now in preview for iOS with it being default renderer in later stable release.

I'll check if there are any noticable changes compared to my previous tests. If not, i guess it's better to wait for Impeller being default and then do some optimisations if needed.

For now i'll close this issue, feel free to reopen it.
