### ISSUE TITLE
Feature: Improve animation fidelity

### ISSUE THREAD

**Issue by davidhicks980** [notDmDrl/pull_down_button#13]
First off, this package is awesome. Excellent work.

I've been playing with the source code to adapt it to our app, and I noticed that the current default animations differ from the native implementation. You may have a reason for having different animations, so I just wanted to throw some animation curves out there in case you'd like to adapt them.

```dart

/// Pull-down menu animation curve.
@internal
const Curve kCurve = ElasticOutCurve(1.0);

/// Pull-down menu reverse animation curve.
@internal
const Curve kCurveReverse = Curves.easeOut;
```

Above animation curve:
https://user-images.githubusercontent.com/59215665/218893846-075baca1-0391-4866-8344-0fac00762362.mp4

Native:
https://user-images.githubusercontent.com/59215665/218894040-6e26a816-6628-418c-92bf-fbd96df0f0a4.mp4

**Comment by notDmDrl** [comment]
Hi @davidhicks980 

There was no particular reason for curves being off except that Apple doesn't provide any info on them, so i guess i took current curves from some other cupertino widget.

Also i attempted to introduce this bouncy curve in one of last big updates but was not satisfied enough with it.

Are your proposed curves based on some Apple docs, taken from somewhere or eyeballed?

Thx

**Comment by davidhicks980** [comment]
Eyeballed, and my curves may not be that close to the actual implementation. My main goal was to replicate a similar elasticity, but it sounds like you've explored it, so no worries if current implementation is preferred. I will try to dig for some type of source code for Apple's curves though.

**Comment by notDmDrl** [comment]
Hi @davidhicks980 

I introduced a new set of curves (including bouncy one) in latest **0.6.0** update. 

###### They're definitely not same as native ones, i doubt it is possible to reverse engineer it anyway 😄
