### ISSUE TITLE
Don't pop or hide the dialog (pull down)

### ISSUE THREAD

**Issue by fadhly-permata** [notDmDrl/pull_down_button#16]
Hi, thanks a lot for making this widget.

Btw, can we make the dialog (pull down) not hide after clicking the item (button, icon, etc) inside it?
to make you clear, see my screenshot

![image](https://user-images.githubusercontent.com/8925077/224893834-86531f31-c5e1-404a-a2fe-8bf6d8251fea.png)

As you can see, I need to make the menu stay shown because I have increase and decrease buttons inside it.

Can you give me any suggestions?

**Comment by notDmDrl** [comment]
Hi @fadhly-permata 

Update **0.6.4** is live with `PullDownMenuItem.tapHandler` added.

Snippet from examples:

```dart
[
  PullDownMenuItem(
    onTap: () => print('This action is called after menu is popped'),
    // A default behaviour
    tapHandler: PullDownMenuItem.defaultTapHandler,
    title: 'Pop menu and call [onTap]',
  ),
  PullDownMenuItem(
    onTap: () => print('This action is called without menu being popped'),
    // A no pop behaviour
    tapHandler: PullDownMenuItem.noPopTapHandler,
    title: 'Call [onTap]',
  ),
  PullDownMenuItem(
    onTap: () => print('This action will never be called'),
    // A "do nothing" behaviour
    tapHandler: (context, onTap) => {},
    title: "Don't call anything",
  ),
]
```

**Comment by fadhly-permata** [comment]
It's work like a charm.. once again thanks a lot
