### ISSUE TITLE
Feature: Add glide between menu items

### ISSUE THREAD

**Issue by iSa1vatore** [notDmDrl/pull_down_button#19]
I tried to add glide between menu items, sent the [PR](https://github.com/notDmDrl/pull_down_button/pull/18). 

At the moment this is a rough draft, to demonstrate how I see the implementation of this feature.

What do you think?

Demo:

https://user-images.githubusercontent.com/42691184/225049398-5173fbc1-106b-4cfb-907a-5852c85b9aef.mov

**Comment by notDmDrl** [comment]
Daaaaamn, i don't think even Flutter repo has this implemented

i'm really impressed 👏
