### ISSUE TITLE
Not sure how to apply theme extension with CupertinoApp

### ISSUE THREAD

**Issue by rikbrown** [notDmDrl/pull_down_button#2]
Hi,

The example for customizing the theme seems to apply to Material but not to CupertinoApps:

```
ThemeData(
  ...,
  extensions: [
    PullDownButtonTheme(
      backgroundColor: Colors.grey,
      iconSize: 24,
      dividerColor: Colors.black,
    ),
  ],
),
```

This won't work for my `CupertinoApp` because it expects a `CupertinoThemeData`, which doesn't have an `extensions` property.

Am I being stupid, or is there a different way to handle this?

Cheers,
Rik.

**Comment by notDmDrl** [comment]
Hi @rikbrown 

`CupertinoThemeData` indeed does not have a way of defining `extensions`.

I have just published update that introduces `PullDownButtonInheritedTheme` as a additional way of defining global `PullDownButtonTheme` (ex.  in `CupertinoApp`).

Consider this example:

```dart
CupertinoApp(
  builder: (context, child) => PullDownButtonInheritedTheme(
    data: const PullDownButtonTheme(
      backgroundColor: Colors.grey,
      iconSize: 24,
      dividerColor: Colors.black,
    ),
    child: child!,
  ),
  home: ...,
)
```

**Comment by rikbrown** [comment]
Perfect, this looks exactly what I wanted. Thank you so much for that fast update! I'll try it shortly.

**Comment by rikbrown** [comment]
Seems to work great from initial testing. Thank you again. I'll close this issue.
