### ISSUE TITLE
Aligning the menu

### ISSUE THREAD

**Issue by Gazizbek** [notDmDrl/pull_down_button#22]
Is there any params to align the menu? In previous version it was done by param offset. In current version this param. In my situation, the button is full width, and I want to align the menu to right.
<img width="356" alt="Screenshot 2023-04-09 at 11 32 54" src="https://user-images.githubusercontent.com/43266026/230756446-01882e83-0a4b-4a56-b8db-db00e9ce280b.png">

**Comment by notDmDrl** [comment]
Hi @Gazizbek 

A fix to this will be added in a midweek update. In the meantime, if critical, you can use `showPullDownMenu` with the desired position.

**Comment by notDmDrl** [comment]
Hi @Gazizbek 

Update **0.8.2** is live with `PullDownButton.buttonAnchor` added.

For your provided example you'll need to do the following update:

```dart
PullDownButton(
  onTap: ...,
  buttonAnchor: PullDownMenuAnchor.end,
  buttonBuilder:...,
)
```

**Comment by ansh-les** [comment]
Thanks for the example @notDmDrl. Works great!

**Comment by Gazizbek** [comment]
Thank you @notDmDrl
