### ISSUE TITLE
background fade-out on Safari with html web-renderer

### ISSUE THREAD

**Issue by KoiFresh** [notDmDrl/pull_down_button#24]
The grey fade out of the background does not working on Safari when the html renderer is used.

What works
- chrome 
- canvaskit

What doesn't
- html renderer on safari

Expected:
![image](https://user-images.githubusercontent.com/60545012/231833250-c2531fd1-f342-466b-b266-da47d59d34f1.png)

Actual:
![image](https://user-images.githubusercontent.com/60545012/231832880-7e3575e1-6792-4dad-888f-5e574fc0ee37.png)

How to reproduce:

1. Build with html renderer:
```bash
flutter run --web-renderer html
```
2. Open in Safari

**Comment by notDmDrl** [comment]
Hi @KoiFresh 

Seems like this is a Flutter-specific issue (see https://github.com/flutter/flutter/issues/98148).

The only thing I can advise you to do is to either remove shadows entirely (set `PullDownMenuRouteTheme.endShadow` to `BoxShadow(color: Colors.transparent)`) or try and find a suitable replacement for the default `PullDownMenuRouteTheme.endShadow` which you can find [here](https://github.com/notDmDrl/pull_down_button/blob/main/lib/src/theme/route_theme.dart#L201)
