### ISSUE TITLE
Transparent pull down menu 

### ISSUE THREAD

**Issue by fredrik-smedberg** [notDmDrl/pull_down_button#28]
Hi!

```
Flutter 3.7.12
pull_down_button: 0.9.1
macOS: 13.3.1a
M1 CPU
```

The dropdown menu seems to get transparency when using the widget with the Flutter web HTML render (`flutter build web --web-renderer html`). If I instead use the default canvas render, like when coding and running in debug mode, the dropdown menu has no transparency.

A snippet of the code I used:
```
PullDownButton(
    buttonBuilder: (context, showMenu) =>
        CupertinoButton(
            onPressed: showMenu,
            padding: EdgeInsets.zero,
            child: Text(selectedSortingMethod),
        ),
    itemBuilder: (context) {
         return <PullDownMenuEntry>[
             PullDownMenuItem(
                 icon: CupertinoIcons.textformat_abc,
                 title: lang.customer_reports_fas_bar_sort_by_alphabetical,
                 onTap: () => context.read<CustomerReportsCubit>().changeSortingMethod(
                                              ReportsSortingMethod.alphabetical))
```

Flutter web with **canvas** render
<img width="325" alt="bild" src="https://github.com/notDmDrl/pull_down_button/assets/21035217/86bf5150-38b3-4f5b-b7ad-e1590f202515">

Flutter web with **html** render
<img width="301" alt="bild" src="https://github.com/notDmDrl/pull_down_button/assets/21035217/181af08e-b396-4ebf-9666-3d5a5dc2565d">

**Comment by notDmDrl** [comment]
Hi @fredrik-smedberg 

Similarly to https://github.com/notDmDrl/pull_down_button/issues/24 this is another Flutter-specific issue (see https://github.com/flutter/flutter/issues/124764 and https://github.com/flutter/flutter/issues/51575).

As a workaround, I would advise using a fully opaque background color in `PullDownMenuRouteTheme`. It seems like you are using the default background color, so you can copy values from [here](https://github.com/notDmDrl/pull_down_button/blob/e5096479bcc464610abebb04159d66d8660434e5/lib/src/theme/route_theme.dart#L192), update opacity to 1, and pass those values to `PullDownButtonTheme.routeTheme`.
