### ISSUE TITLE
Wider menu items?

### ISSUE THREAD

**Issue by llorenzo** [notDmDrl/pull_down_button#3]
The display of the menu items is a bit narrow on the iPad. Is it possible to widen it?

**Comment by notDmDrl** [comment]
Hi @llorenzo 

As far as i know, pull-down menus in iOS and iPadOS have equal width of 250px (i'll double-check it tomorrow 'cause i can't quite remeber if iPadOS even uses pull-down menus or something different).

But i'll look into adding possibility to change menu's width (probably somewhere in the end of this week).

**Comment by notDmDrl** [comment]
Quick follow up to my yesterdays comment and indeed both iOS and iPadOS are using the same 250px width pull-down menu.

I also checked if there is any width difference between native and my flutter version - they're also same.

Since they're equal, i'd say that it should stay that way.

**Comment by llorenzo** [comment]
Yes, your propably right. The thing is, I would like to strech the iOS design in my particular case...

**Comment by notDmDrl** [comment]
> The thing is, I would like to strech the iOS design in my particular case...

I think there is no problem in that really, i'll try to get update with this out in a few hours.

**Comment by notDmDrl** [comment]
@llorenzo 

I have just published update that adds menu width customization.

Example:

```
PullDownButtonTheme(
  widthConfiguration: PullDownMenuWidthConfiguration(400),
)
```

or

```
PullDownButton(
  itemBuilder: ...,
  buttonBuilder: ...,
  widthConfiguration: PullDownMenuWidthConfiguration(400),
)
```

**Comment by llorenzo** [comment]
Works perfect! Thank you very much.
