### ISSUE TITLE
Possibility to not dismiss menu after item button tap

### ISSUE THREAD

**Issue by vleeuwenmenno** [notDmDrl/pull_down_button#30]
Is there a possibility, there could be a feature added allowing me to tap an item and not close the menu?
I have a use case for this to increase or decrease a batch size, and having to re-open the menu is cumbersome and not UX friendly.

**Comment by notDmDrl** [comment]
Hi @vleeuwenmenno 

This functionality exists since update **0.6.4**.

See https://github.com/notDmDrl/pull_down_button/issues/16#issuecomment-1467715506 for an example.

**Comment by vleeuwenmenno** [comment]
This seems to work well indeed, but is there a way to update the menu state after this, as these buttons change the label of a button above this action row?

```
PullDownMenuActionsRow.medium(
            items: [
              PullDownMenuItem(
                onTap: () {
                  imageJobProvider.batchSize++;

                  if (imageJobProvider.batchSize > 16) {
                    imageJobProvider.batchSize = 16;
                  }
                },
                title: 'Increase batch',
                icon: CupertinoIcons.plus,
                tapHandler: PullDownMenuItem.noPopTapHandler,
              ),
              PullDownMenuItem(
                onTap: () {
                  imageJobProvider.batchSize--;

                  if (imageJobProvider.batchSize < 1) {
                    imageJobProvider.batchSize = 1;
                  }
                },
                title: 'Decrease batch',
                icon: CupertinoIcons.minus,
                tapHandler: PullDownMenuItem.noPopTapHandler,
              ),
            ],
          ),
```

**Comment by notDmDrl** [comment]
@vleeuwenmenno 

Unfortunately, there is no direct way to change any item's state once the menu is opened, but you might refer to https://github.com/notDmDrl/pull_down_button/issues/27#issuecomment-1545380358. There is an example of `ValueNotifier` solution that you can repurpose using your own state management solution
