### ISSUE TITLE
How to customized the width

### ISSUE THREAD

**Issue by luohao123** [notDmDrl/pull_down_button#33]
How to customized the width

**Comment by notDmDrl** [comment]
Hi @luohao123 

There is already a functionality for this. To customize the menu's width use `PullDownButtonTheme.routeTheme.width` or in any menu widget such as `PullDownMenuButton` using `routeTheme.width`.

Example: 

```dart
PullDownButtonTheme(
  routeTheme: PullDownMenuRouteTheme(
    width: 300,
  ),
)
```

or 

```dart
PullDownButton(
  itemBuilder: ...,
  buttonBuilder: ...,
  routeTheme: PullDownMenuRouteTheme(
    width: 300,
  ),
)
```
