### ISSUE TITLE
Vertical positioning off

### ISSUE THREAD

**Issue by llorenzo** [notDmDrl/pull_down_button#35]
The is not appearing in the right position. It appears way below the anchor. PullDownMenuPosition.over nor automatic does help.
I had to revert to 0.5.1 where it worked fine. From 0.6.0 on it throws a nukk valu Error. From 9.0.0 it works again but with the wrong positioning...
The Anchor created by the buttonBuilder is placed in a Subpage and inside a SingleChildScrollView.

**Comment by notDmDrl** [comment]
Hi @llorenzo 

Can you please provide screenshots or a sample code with this issue?

Up until version 0.9.0 the positioning behavior was directly compared with native variant with a few pixels difference at most so.

I'll look further into this once screenshots/sample code is provided

Thanks

**Comment by llorenzo** [comment]
Hey, I'm in the mids of a project and have little time to give more information. Also sourcecode is complex and long and disclosed... But basically I have a nested Navigator through auto_route. In the nested Navigator I have SingleChildScrollView with a Column. Hope that helps.

**Comment by notDmDrl** [comment]
No reproducible example was provided, closing.
