### ISSUE TITLE
How can i remove padding?

### ISSUE THREAD

**Issue by fyxtc** [notDmDrl/pull_down_button#40]
If the button is smaller than some value, it will be added by some padding automatically

```
buttonBuilder: (context, showMenu) => CupertinoButton(
                      onPressed: showMenu,
                      padding: EdgeInsets.zero,
                      child: Container(
                        color: Colors.red,
                        padding: EdgeInsets.zero,
                        child: const Icon(CupertinoIcons.rectangle_grid_2x2),
                        // child: Text("11"),
                      ),
                    )
```

<img width="62" alt="image" src="https://github.com/notDmDrl/pull_down_button/assets/3948940/b7608c33-e7f5-4420-960b-f2c3682c6576">

**Comment by notDmDrl** [comment]
Hi @fyxtc,

Yes you are right, if the button's height is less than 44px there will be an additional padding applied to the menu position. This behavior was taken directly from native menus on iOS 16, so unless they changed that in iOS 17 I am not sure I want to change it.

**Comment by fyxtc** [comment]
@notDmDrl Thank you for reply. I solved by use GestureDetector
```
buttonBuilder: (context, showMenu) => GestureDetector(
                    onTap: showMenu,
                    // padding: EdgeInsets.zero,
                    child: const Icon(CupertinoIcons.rectangle_grid_2x2),
                  )
```
