### ISSUE TITLE
How to make the background color no blur with pure color?

### ISSUE THREAD

**Issue by lucasjinreal** [notDmDrl/pull_down_button#43]
How to make the background color no blur with pure color?

**Comment by notDmDrl** [comment]
Hi @lucasjinreal 

The only way to remove blur from the menu background is by providing a fully opaque color to `PullDownMenuRouteTheme.backgroundColor`.

**Comment by lucasjinreal** [comment]
@notDmDrl  thanks, is there a way to remove the divider (tiny one) and make the icon and text reverse position? Icon on the front in row.

**Comment by notDmDrl** [comment]
@lucasjinreal 

As of version 0.9.0, small dividers are inserted automatically. This was done to match the default behavior in SwiftUI Menu API (in SwiftUI only big dividers are inserted manually), so unfortunately, it is impossible. It is, however, possible to manually control small divider placement in menus in versions before 0.9.0.

Icon and text in reverse position are not in iOS guidelines, so there is no way to do so by default. You can try to create your custom menu item based on existing code ([here](https://github.com/notDmDrl/pull_down_button/blob/main/lib/src/items/item.dart#L446)) with your specific design requirements.
