### ISSUE TITLE
Force menu to pop in from top right to bottom left

### ISSUE THREAD

**Issue by falt008** [notDmDrl/pull_down_button#46]
I want to use this package for a button at the right end of a Sidebar, however the menu always pops in from top left to bottom right. This means that either the menu pops into the app content next to the sidebar (Variant 1) or I use menu Offset to shift the menu to the left (Variant 2) but it feels weird if the menu pops from somewhere the user has not clicked.

Variant 1
![image](https://github.com/notDmDrl/pull_down_button/assets/87002640/664620ff-1159-4981-8043-651e2b2e50ef)

Variant 2
![image](https://github.com/notDmDrl/pull_down_button/assets/87002640/c822dace-64d9-4222-95b9-3daa697b6718)

What I would need is that it can be specified that the menu should pop from top right to bottom left so I could use Variant 2 in this way:

![image](https://github.com/notDmDrl/pull_down_button/assets/87002640/a50c2434-1645-4bff-8ed0-af1cede54b5b)

Can this be done with this package? The menu is exactly what I need and it looks super cool.

**Comment by notDmDrl** [comment]
Hi @falt008

While I distinctly remember seeing that native menu pop over to the right in those situations (like on your first screenshot), this is a fairly reasonable feature request.

Update **0.9.4** is live with `PullDownButton.animationAlignmentOverride` added.

For your provided example you could try the following:

```dart
PullDownButton(
  itemBuilder: ...,
  buttonBuilder: ...,
  // ignore: invalid_use_of_internal_member
  menuOffset: PullDownMenuRouteTheme.resolve(
    context,
    routeTheme: null,
  ).width!,
  animationAlignmentOverride: Alignment.topRight,
  buttonAnchor: PullDownMenuAnchor.end,
)
```

Sadly it is not a pretty solution I would say but should be good enough 🥲

**Comment by falt008** [comment]
Hi @notDmDrl, wow this was fast - this works perfectly and is exactly what I need! 
Thank you very much!
