### ISSUE TITLE
Prevent menu closing after selected item?

### ISSUE THREAD

**Issue by WeighingDog** [notDmDrl/pull_down_button#47]
Hi!
Is there any way to prevent menu close after item selection?

**Comment by notDmDrl** [comment]
Hi @WeighingDog,

Yes there is - see this particular [example](https://github.com/notDmDrl/pull_down_button/blob/main/example%2Flib%2Fsrc%2Ftap_handler.dart) for various ways to handle the menu item tap, including preventing menu from closing.
