### ISSUE TITLE
I want to change the position of Pull Down Button to under or above depending on the situation.

### ISSUE THREAD

**Issue by etgkqo** [notDmDrl/pull_down_button#5]
I want to change the position of Pull Down Button to under or above depending on the situation as shown in the video below.
Please help me!

https://user-images.githubusercontent.com/16192326/184875868-bb3b7071-b26d-492a-acef-b8ee61111213.mp4

**Comment by notDmDrl** [comment]
@etgkqo 

There is no simple way to do that currently and unfortunately i don't have any free time to look into it myself (and will not have any till mid September)

In the meantime maybe you can try getting item position using this [stackoverflow answer](https://stackoverflow.com/a/58788092), and then, based on it and a screen height, change `PullDownButton`'s position to `PullDownMenuPosition.above` or `PullDownMenuPosition.below`.

**Comment by etgkqo** [comment]
@notDmDrl  Thanks! I'll try the way you told me!

**Comment by notDmDrl** [comment]
Hey @etgkqo 

I finally got some time to do this, the update is live.

There is now a new `PullDownMenuPosition.automatic` which should be exactly what you need.
