### ISSUE TITLE
Can leading widget for PullDownMenuHeader be further customized?

### ISSUE THREAD

**Issue by mark8044** [notDmDrl/pull_down_button#50]
First, phenomenal work on this.  Its quite slick package.

The leading widget right now will always put your items in a grey box in iOS style.  But in the future, iOS style may change, so we should have the ability to customize that leading widget.  For example, no grey box with drop shadow, etc...

Or at the very least make the leading widget optional so we are not forced to put something there

**Comment by notDmDrl** [comment]
Hi @mark8044, 

> But in the future, iOS style may change, so we should have the ability to customize that leading widget.

Yes, this might be a problem in the future as I no longer actively maintain this package since I don't have access to any Apple products anymore so I can't even verify if UI-related stuff is correct since most in-depth design docs they provide are in Sketch which is MacOS exclusive app 😞

This is a valid request and I'll try to come up with some update for this soon

> Or at the very least make the leading widget optional so we are not forced to put something there

Wouldn't making the leading widget optional be redundant? You might as well use the normal `PullDownMenuItem`, no? But I guess that might also be nice to have

**Comment by mark8044** [comment]
> Hi @mark8044,
> 
> > But in the future, iOS style may change, so we should have the ability to customize that leading widget.
> 
> Yes, this might be a problem in the future as I no longer actively maintain this package since I don't have access to any Apple products anymore so I can't even verify if UI-related stuff is correct since most in-depth design docs they provide are in Sketch which is MacOS exclusive app 😞
> 
> This is a valid request and I'll try to come up with some update for this soon
> 
> > Or at the very least make the leading widget optional so we are not forced to put something there
> 
> Wouldn't making the leading widget optional be redundant? You might as well use the normal `PullDownMenuItem`, no? But I guess that might also be nice to have

You know of course you are right!  Im an idiot.  I did not realized that `PullDownMenuItem` still gave you the options of the `subtitle` and `icon`, so yes that is a better implementation for my use case.  

I still like the idea of being able to update the icon on the left, but this is now very low priority :)

Thanks so much!

**Comment by notDmDrl** [comment]
Hi @mark8044 

Update **0.10.0** is live with `leadingBuilder` added to `PullDownMenuHeader`. This should be good enough as it allows for complete freedom of choosing what the leading widget will look like.

Snippet from examples:

```dart
PullDownMenuHeader(
  leadingBuilder: (context, constraints) => ConstrainedBox(
    constraints: constraints,
    child: const FlutterLogo(),
  ),
  title: 'Title',
)
```
