### ISSUE TITLE
When tapping a selectable item, the menu closes

### ISSUE THREAD

**Issue by mark8044** [notDmDrl/pull_down_button#56]
Im making a group of selectable items, and when the user tapsone of the selectable items the menu closes.  The selection change is correctly recorded but id like the menu to stay open while the user decides between selections.  Is the the intended implementation or is this a problem with my implementation?   

If this is intended, is it possible to keep the menu open somehow?

**Comment by notDmDrl** [comment]
Hi @mark8044 

Yes, this is intended. Yes. it is possible to keep the menu open after tapping and it is possible to update the menu's selectable items state without closing the menu. Please see the following issues: 

- To keep the menu open - https://github.com/notDmDrl/pull_down_button/issues/16#issuecomment-1467715506 and https://github.com/notDmDrl/pull_down_button/issues/47#issuecomment-2106748739
- To update the menu's selectable items state while the menu is open - https://github.com/notDmDrl/pull_down_button/issues/27#issuecomment-1545380358 and https://github.com/notDmDrl/pull_down_button/issues/51#issuecomment-2163443292

**Comment by mark8044** [comment]
Thanks much! reading up on all this now
