### ISSUE TITLE
macOS: Error on menu scrolling

### ISSUE THREAD

**Issue by intonarumori** [notDmDrl/pull_down_button#58]
When I present a pull down menu with a lot of items I get this error on macOS.

```
FlutterError (The Scrollbar's ScrollController has no ScrollPosition attached.
A Scrollbar cannot be painted without a ScrollPosition.
The Scrollbar attempted to use the provided ScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to.
When providing your own ScrollController, ensure both the Scrollbar and the Scrollable widget use the same one.)
```

The code is something like this:

```
showPullDownMenu(
            context: context,
            items: items
                .asMap()
                .entries
                .map<PullDownMenuItem>((e) => PullDownMenuItem.selectable(
                      onTap: () => onChange(e.key),
                      title: e.value,
                      selected: e.key == selectedIndex,
                    ))
                .toList(),
            position: rect,
          );
```

What do you think?

**Comment by notDmDrl** [comment]
Hi @intonarumori 

I replicated the issue on Windows in the example app even with a few items present. Somehow I managed to miss this [breaking change](https://docs.flutter.dev/release/breaking-changes/default-desktop-scrollbars) 😕

Update **0.10.2** is live with fixes for the issue. Please try it to verify that it also works on MacOS (in case it somehow fixes only Windows scrollbar issues ☹️). Thx

**Comment by intonarumori** [comment]
@notDmDrl 
Thank you for the fast reply, I can confirm it has been fixed for macOS as well.
Really appreciate the quick fix, I'm closing this issue.
