### ISSUE TITLE
Add onHoverColor property

### ISSUE THREAD

**Issue by rmahmadkhan** [notDmDrl/pull_down_button#6]
Usually pull down buttons on web have color change on hover over the action item.
See the following example:

<img width="156" alt="Screenshot 2022-08-29 at 11 57 46 PM" src="https://user-images.githubusercontent.com/46877003/187287929-d6735d0f-813c-403d-92bd-373956b1fda7.png">

Following properties maybe needed:
- onHoverColor
- onHoverTextStyle or onHoverTextColor
- onHover callback

**Comment by notDmDrl** [comment]
Hi @rmahmadkhan 

I don't think that in iOS pull-down menus have onHover properties.

This package attempts to recreate a mobile (iOS) look for pull-down menus.

For more desktop/web apple-like menus you should probably try this: https://pub.dev/packages/macos_ui#pulldownbutton

If you still want to use my package please let me know, I'll try to come up with something.

**Comment by rmahmadkhan** [comment]
Hi @notDmDrl 

Thank you for replying. As you suggested, I tried that and other packages as well. But your package suits best for my need as it is very simple. I just need the colorOnHover (highlight color) property.

I really wish I could open a pull request for this but too busy with my work already.

It would be really great if you can make sometime to add that.

**Comment by notDmDrl** [comment]
@rmahmadkhan ok, no promises but i'll try to do it tomorrow 😃

**Comment by rmahmadkhan** [comment]
@notDmDrl Awesome! Grateful for that!

**Comment by rmahmadkhan** [comment]
@notDmDrl Thank you for doing this. 
this is almost what I need. but need onHoverTextStyle property as well. As, it won't change the color on hover the item :(

**Comment by notDmDrl** [comment]
@rmahmadkhan gotcha, might squeeze in a bit of time tomorrow morning for it

**Comment by notDmDrl** [comment]
@rmahmadkhan 

Another update is live, this time with `onHoverTextStyle` support.

```
PullDownButtonTheme(
  onHoverTextStyle: ...,
)
```

or

```
PullDownMenuItem(
  onTap: ...,
  title: ...,
  onHoverTextStyle: ...,
)
```

**Comment by rmahmadkhan** [comment]
@notDmDrl Thank you for taking out time and doing this. Appreciated.
