### ISSUE TITLE
PullDownMenuHeader Issue

### ISSUE THREAD

**Issue by xykadra** [notDmDrl/pull_down_button#60]
Why leading widget cannot be edited? 
It can only be ColoredBox and If I try to manipulate it there is some kind of shading below it?
<img width="52" alt="image" src="https://github.com/user-attachments/assets/3c185548-b981-41a8-8879-cbfd73f96707">

**Comment by notDmDrl** [comment]
Hi @xykadra 

> Why leading widget cannot be edited?
> It can only be ColoredBox and If I try to manipulate it there is some kind of shading below it?

The default styling was made after the way it was defined in the iOS Sketch guidelines.

To create a fully custom leading widget use `leadingBuilder`. Additionally you can check out https://github.com/notDmDrl/pull_down_button/issues/50#issuecomment-2266680424
