### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by sinahamedi67** [notDmDrl/pull_down_button#7]
Hi,
In RTL languages, paddings are not correct, checkmark padding should be on the left, and icon padding should be on the right. 

![image](https://user-images.githubusercontent.com/78305390/194964921-e0e0d460-7f5e-411d-8faf-38e367519e6e.png)

I just reversed the paddings in `buildChild` method of the `SelectablePullDownMenuItem` class. Now it's fine for RTL languages:

![image](https://user-images.githubusercontent.com/78305390/194965704-6c4eb8d6-c839-4fc2-8dea-4f3c77c3de25.png)

But there should be a better way to make it locale-aware. So it works in both directions.

Thanks in advance

**Comment by notDmDrl** [comment]
Hi @sinahamedi67 

I've published an update with fix for this.

If there are still some problems with RTL please let me know.
