### ISSUE TITLE
is it possible to configure PullDownButton outer shadow?

### ISSUE THREAD

**Issue by aMGLn** [notDmDrl/pull_down_button#8]
As I mentioned in the title, I can not find any possibility to change outer shadow of PullDownButton. Is there any option to change that?

**Comment by notDmDrl** [comment]
Hi @aMGLn, as of right now you can't do it

This sounds reasonable though, will add this in one of future updates

**Comment by notDmDrl** [comment]
Hi @aMGLn 

You can now customise shadows using `PullDownMenuRouteTheme` (begin and end shadows):

```dart
PullDownButton(
  routeTheme: PullDownMenuRouteTheme(
    beginShadow: BoxShadow(color: Colors.red.withOpacity(0)),
    endShadow: BoxShadow(color: Colors.red.withOpacity(0.1)),
  ),
)
```

It's also possible to set global shadow values in `PullDownButtonTheme.routeTheme`.

**Comment by aMGLn** [comment]
Thank you, I will try the new version
