### ISSUE TITLE
Property to disable blur effect

### ISSUE THREAD

**Issue by mario-jerkovic** [notDmDrl/pull_down_button#9]
Hi 👋, first things first have to say awesome work for the lib.

I was just wondering if it would make sense to create a prop which could disable the blur effect, as flutter has tons of issues when the blur is applied to a widget over some native view like Google maps and etc. Specifically, in our case we are using this widget over the native Map library and blur is not aligned with the PullDownButton. I know that this specific issue is with flutter and I have already created couple of issues on their Github repo, but until that is fixed it would be awesome that blur can be enabled/disabled via prop.

Thanks

**Comment by notDmDrl** [comment]
Hi @mario-jerkovic 

Update **0.4.1** is live. To disable blur effect simply use fully opaque background color.

**Comment by mario-jerkovic** [comment]
@notDmDrl It works like a charm, thank you 👍
